language: cpp
dist: trusty
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

before_install:
  - sudo apt-get -qq update
  
install:
  - sudo apt-get install -y cmake libboost-all-dev libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo mv libgtest* /usr/lib/
  - cd $TRAVIS_BUILD_DIR

script:
  - mkdir build
  - cd build
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5
  - cmake --build . -- -j2 
  - ctest .
